source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'sqlite3-ruby', '1.3.3', :require => 'sqlite3'
gem 'taps', '0.3.19'

#group :development do
#   gem 'faker', '0.9.5'
#   gem 'rspec-rails', '2.5.0'
#end

#group :test do
#   gem 'rspec', '2.5.0'
#   gem 'webrat', '0.7.3'
#   gem 'factory_girl_rails', '1.0.1'
#end

